stages:
- name: Code Review--run Checkmarx test
  steps:
  - runScriptConfig:
      image: iiiorg/checkmarx-runner
      shellScript: cd /usr/src/app; ls; echo ${api_orign}; node app.js;
    env:
      git_url: ${CICD_GIT_URL}
      git_branch: ${CICD_GIT_BRANCH}
      git_commit_id: ${CICD_GIT_COMMIT}
      verbose: true
    envFrom:
    - sourceName: nexus
      sourceKey: api-origin
      targetKey: api_origin
    - sourceName: nexus
      sourceKey: username
      targetKey: api_username
    - sourceName: nexus
      sourceKey: password
      targetKey: api_password
    - sourceName: checkmarx
      sourceKey: username
      targetKey: username
    - sourceName: checkmarx
      sourceKey: password
      targetKey: password
    - sourceName: checkmarx
      sourceKey: client-secret
      targetKey: client_secret
    - sourceName: checkmarx
      sourceKey: cm-url
      targetKey: cm_url
